### ISSUE TITLE
Problems with wiping save

### ISSUE THREAD

**Issue by Bruhmandowg** [lucasvinbr/GTA5GangMod#15]
when i started i had a ton of money and maxed out my gang since i didn't know what i was doing. Ive been looking for a way to reset my progress, pls help.

**Comment by lucasvinbr** [comment]
editing your GangData.xml file should be enough:

Find your gang there (it should have the name you've set) and either edit the values so that they are no longer maxed out or remove your gang from the file (delete/cut all of your gang's <gang> block). A new "Player's Gang" will be generated once scripts are loaded again (if you reload scripts or open the game again)
